alias: Verlichting - Aan bij donker tussen 08:00 en 23:30
description: Zet de lampen aan als het donker wordt en laat ze minimaal 15 minuten branden.
triggers:
  - trigger: numeric_state
    entity_id: sensor.weerstation_licht
    below: 400
    for:
      minutes: 2
  - trigger: homeassistant
    event: start
conditions:
  - condition: time
    after: "08:00:00"
    before: "23:30:00"
  - condition: numeric_state
    entity_id: sensor.weerstation_licht
    below: 400
actions:
  - action: switch.turn_on
    target:
      entity_id:
        - switch.keuken_led_sonoff_relay
        - switch.woonkamer_lamp_kachel
        - switch.sonoff_1000af2fcd_1
  - delay:
      minutes: 15
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.weerstation_licht
            above: 400
        sequence:
          - action: switch.turn_off
            target:
              entity_id:
                - switch.keuken_led_sonoff_relay
                - switch.woonkamer_lamp_kachel
                - switch.sonoff_1000af2fcd_1
    default:
      - wait_for_trigger:
          - trigger: numeric_state
            entity_id: sensor.weerstation_licht
            above: 400
            for:
              minutes: 2
          - trigger: time
            at: "23:30:00"
      - action: switch.turn_off
        target:
          entity_id:
            - switch.keuken_led_sonoff_relay
            - switch.woonkamer_lamp_kachel
            - switch.sonoff_1000af2fcd_1
mode: single
