alias: Verlichting - uit bij voldoende licht
description: Zet de lampen uit zodra het buiten licht genoeg is. zonsopkomst.
triggers:
  - entity_id: sensor.weerstation_licht
    above: 400
    for:
      minutes: 10
    trigger: numeric_state
conditions: []
actions:
  - target:
      entity_id:
        - switch.keuken_led_sonoff_relay
        - switch.woonkamer_lamp_kachel
        - switch.sonoff_1000af2fcd_1
    action: switch.turn_off
mode: single
